services:
  - type: web
    name: pingme-dashboard
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: REDIS_URL
        fromService:
          name: pingme-redis
          type: redis
          property: connectionString

  - type: worker
    name: pingme-worker
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: worker/Dockerfile
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: REDIS_URL
        fromService:
          name: pingme-redis
          type: redis
          property: connectionString

databases:
  - name: pingme-redis
    plan: free
    ipAllowList: []